openapi: 3.0.0
info:
  title: Gestión de Transacciones
  version: 1.0.0
  description: API para gestionar transacciones bancarias

paths:
  /transacciones/{id}:
    get:
      tags:
        - transacciones
      summary: Obtener transacción por ID
      description: Obtiene los detalles de una transacción específica
      operationId: obtenerTransaccion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID de la transacción
      responses:
        '200':
          description: Detalles de la transacción
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaccion'
        '404':
          description: Transacción no encontrada
    delete:
      tags:
        - transacciones
      summary: Eliminar transacción
      description: Elimina una transacción específica
      operationId: eliminarTransaccion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID de la transacción
      responses:
        '204':
          description: Transacción eliminada exitosamente
        '404':
          description: Transacción no encontrada

components:
  schemas:
    Transaccion:
      type: object
      required:
        - tipo
        - monto
        - fecha
      properties:
        id:
          type: string
          description: ID único de la transacción
        tipo:
          type: string
          description: Tipo de transacción
          enum:
            - DEPOSITO
            - RETIRO
            - TRANSFERENCIA
        monto:
          type: number
          format: float
          description: Monto de la transacción
          minimum: 0
        fecha:
          type: string
          format: date-time
          description: Fecha y hora de la transacción
        cuentaOrigenId:
          type: string
          description: ID de la cuenta de origen (requerido para retiros y transferencias)
        cuentaDestinoId:
          type: string
          description: ID de la cuenta de destino (requerido para transferencias)
